### ISSUE TITLE
FreeRouting does not work when layer names change. 

### ISSUE THREAD

**Issue by leoheck** [rbuj/FreeRouting#8]
Hi, I am trying to use your fork, and I receive error bellow. Do you know if I am doing something wrong or how I can fix this? My board has 4 layers.

This is the B.Cu inside of the dsn file.

```
    (layer B.Cu
      (type jumper)
      (property
        (index 3)
      )
    )
```

I just renamed all layer names to (type signal) and FreeRouter just opened my design.
In kicad the layer type is something written by the user, so it is an issue to use it. What do you think?

```
Structure.read_layer_scope: unknown layer type jumper
Dec 06, 2017 11:38:25 AM net.freerouting.freeroute.designformats.specctra.Plane read_scope
SEVERE: null
net.freerouting.freeroute.designformats.specctra.ReadScopeException: Layer name B.Cu not found in layer structure 
	at net.freerouting.freeroute.designformats.specctra.Shape.read_layer_shape_scope(Shape.java:82)
	at net.freerouting.freeroute.designformats.specctra.Polygon.read_polygon_scope(Polygon.java:45)
	at net.freerouting.freeroute.designformats.specctra.Shape.read_shape_scope(Shape.java:53)
	at net.freerouting.freeroute.designformats.specctra.Area.read_area_scope(Area.java:56)
	at net.freerouting.freeroute.designformats.specctra.Plane.read_scope(Plane.java:90)
	at net.freerouting.freeroute.designformats.specctra.Structure.read_scope(Structure.java:864)
	at net.freerouting.freeroute.designformats.specctra.ScopeKeyword.read_scope(ScopeKeyword.java:110)
	at net.freerouting.freeroute.designformats.specctra.DsnFile.read(DsnFile.java:71)
	at net.freerouting.freeroute.interactive.BoardHandling.import_design(BoardHandling.java:964)
	at net.freerouting.freeroute.BoardFrame.read(BoardFrame.java:258)
	at net.freerouting.freeroute.BoardFrame.<init>(BoardFrame.java:141)
	at net.freerouting.freeroute.MainAppController.lambda$create_board_frame$0(MainAppController.java:94)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

AutorouteSettings.read_layer_rule: layer not found
```

**Comment by rbuj** [comment]
We use the layer type to know whether the layer should be used for routing.
